export const nbaFields = [
  "away_stats",
  "home_stats",
  "away_totals",
  "home_totals",
];

export const nbaPlayerFields = [
  "last_name",
  "first_name",
  "display_name",
  "position",
  "minutes",
  "points",
  "assists",
  "turnovers",
  "steals",
  "blocks",
  "field_goals_attempted",
  "field_goals_made",
  "three_point_field_goals_attempted",
  "three_point_field_goals_made",
  "free_throws_attempted",
  "free_throws_made",
  "defensive_rebounds",
  "offensive_rebounds",
  "personal_fouls",
  "team_abbreviation",
  "is_starter",
  "field_goal_percentage",
  "three_point_percentage",
  "free_throw_percentage",
];
